[package]
name = "howmanysmall/get-seasons"
description = "A library for getting when a season starts given a year."
version = "1.0.0"
license = "MIT"
registry = "https://github.com/UpliftGames/wally-index"
realm = "shared"
exclude = [
	"docs", ".moonwave", ".vscode", "changelog.md", "README.md", ".gitignore",
	"aftman.toml", "moonwave.toml", "selene.toml", "stylua.toml", "sourcemap.json",
	"tsconfig.json", "package.json", "package-lock.json", ".eslintrc", ".prettierrc",
	"node_modules", "testez.yml", "testez.d.lua", "test.project.json"
]

[dependencies]
